name: Trigger Release rollback

on:
  release:
    types: [deleted]

jobs:
  handle_release:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger release rollback
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: curl -X POST --url 'https://circleci.com/api/v2/project/gh/${{ github.repository }}/pipeline'
          --header 'circle-token:${{ secrets.CIRCLECI_PIPELINE_LAUNCH_TOKEN }}'
          --header 'content-type:application/json'
          --data '{"branch":"${{ github.event.release.target_commitish }}", "parameters":{"RELEASE_VERSION":"${{ github.event.release.tag_name }}", "IS_ROLLBACK":true, "RELEASE_ID":"${{ github.event.release.id }}", "PRIMARY_RELEASE_BRANCH":"${{ github.event.release.target_commitish }}"} }'
